import { TYPES } from './engines.js';

/* Converting between database schema (ERD) code and SQL, without AI. */

const RESERVED = new Set(['user', 'order', 'group', 'table', 'select', 'from', 'where', 'key', 'index', 'references', 'check',
  'default', 'desc', 'asc', 'limit', 'offset', 'role', 'column', 'primary', 'foreign', 'constraint', 'values', 'to', 'by', 'end']);
const quoter = dialect => name => (/^[a-z_][a-z0-9_]*$/.test(name) && !RESERVED.has(name) ? name : dialect === 'mysql' ? '`' + name + '`' : '"' + name.replace(/"/g, '""') + '"');

// Common ERD type names to SQL types. Anything else is passed through as written.
const TYPE_MAP = {
  postgres: { string: 'TEXT', str: 'TEXT', text: 'TEXT', varchar: 'VARCHAR(255)', int: 'INTEGER', integer: 'INTEGER', bigint: 'BIGINT', number: 'NUMERIC', numeric: 'NUMERIC',
    decimal: 'NUMERIC', float: 'REAL', double: 'DOUBLE PRECISION', bool: 'BOOLEAN', boolean: 'BOOLEAN', timestamp: 'TIMESTAMP', timestamptz: 'TIMESTAMPTZ',
    datetime: 'TIMESTAMP', date: 'DATE', time: 'TIME', uuid: 'UUID', json: 'JSONB', jsonb: 'JSONB', blob: 'BYTEA', bytes: 'BYTEA', serial: 'SERIAL' },
  mysql: { string: 'VARCHAR(255)', str: 'VARCHAR(255)', text: 'TEXT', varchar: 'VARCHAR(255)', int: 'INT', integer: 'INT', bigint: 'BIGINT', number: 'DECIMAL(18,4)', numeric: 'DECIMAL(18,4)',
    decimal: 'DECIMAL(18,4)', float: 'FLOAT', double: 'DOUBLE', bool: 'BOOLEAN', boolean: 'BOOLEAN', timestamp: 'TIMESTAMP', timestamptz: 'TIMESTAMP',
    datetime: 'DATETIME', date: 'DATE', time: 'TIME', uuid: 'CHAR(36)', json: 'JSON', jsonb: 'JSON', blob: 'BLOB', bytes: 'BLOB', serial: 'INT AUTO_INCREMENT' },
};
const sqlType = (t, dialect) => (t ? TYPE_MAP[dialect][t.toLowerCase()] || t.toUpperCase() : dialect === 'mysql' ? 'VARCHAR(255)' : 'TEXT');

export const DIALECTS = [['postgres', 'PostgreSQL'], ['mysql', 'MySQL']];

// ERD code -> CREATE TABLE statements, then foreign keys from relationships that name their columns.
export function erdToSql(code, dialect = 'postgres') {
  const m = TYPES.erd.E.parse(code || ''), q = quoter(dialect);
  const out = [`-- Generated by Linework from "${m.title || 'database schema'}" (${dialect === 'mysql' ? 'MySQL' : 'PostgreSQL'})`, ''];
  m.tables.forEach(t => {
    const cols = t.fields.map(f => `  ${q(f.name)} ${sqlType(f.type, dialect)}${f.key === 'uq' ? ' UNIQUE' : ''}`);
    const pk = t.fields.filter(f => f.key === 'pk').map(f => q(f.name));
    if (pk.length) cols.push(`  PRIMARY KEY (${pk.join(', ')})`);
    out.push(`CREATE TABLE ${q(t.id)} (`, (cols.length ? cols : [`  id ${sqlType('', dialect)}`]).join(',\n'), ');', '');
  });
  const fks = [], notes = [];
  m.rels.forEach(r => {
    // The "many" side holds the foreign key. One-to-one: the left side holds it.
    let from, fc, to, tc;
    if (r.card === '>' || r.card === '-') [from, fc, to, tc] = [r.a, r.af, r.b, r.bf];
    else if (r.card === '<') [from, fc, to, tc] = [r.b, r.bf, r.a, r.af];
    else { notes.push(`-- ${r.a} <> ${r.b} is many-to-many: add a join table with a foreign key to each.`); return; }
    if (!fc || !tc) { notes.push(`-- ${r.a} ${r.card} ${r.b}: name the columns (${from}.<column> ${r.card === '<' ? '<' : '>'} ${to}.<column>) to get a foreign key.`); return; }
    fks.push(`ALTER TABLE ${q(from)} ADD FOREIGN KEY (${q(fc)}) REFERENCES ${q(to)} (${q(tc)});`);
  });
  if (fks.length) out.push(...fks, '');
  if (notes.length) out.push(...notes, '');
  return out.join('\n').replace(/\n+$/, '\n');
}

/* SQL -> ERD code. Reads CREATE TABLE (inline and table-level keys, REFERENCES, FOREIGN KEY)
   and ALTER TABLE ... ADD [CONSTRAINT x] FOREIGN KEY. Everything else is ignored. */
const unq = s => s.trim().replace(/^[`"[]|[`"\]]$/g, '');
const lastPart = s => unq(s.split('.').pop());
const ident = s => lastPart(s).replace(/[^\w-]/g, '_');

// Split on commas that aren't inside brackets.
function splitTop(s) {
  const out = []; let depth = 0, cur = '';
  for (const ch of s) {
    if (ch === '(') depth++;
    if (ch === ')') depth--;
    if (ch === ',' && depth === 0) { out.push(cur); cur = ''; } else cur += ch;
  }
  if (cur.trim()) out.push(cur);
  return out.map(x => x.trim()).filter(Boolean);
}
// The body of "CREATE TABLE x ( ... )", with matching brackets.
function bodyAt(sql, i) {
  let depth = 0;
  for (let j = i; j < sql.length; j++) {
    if (sql[j] === '(') depth++;
    else if (sql[j] === ')' && --depth === 0) return { body: sql.slice(i + 1, j), end: j };
  }
  return null;
}
const TYPE_BACK = { 'character varying': 'varchar', 'double precision': 'double', 'timestamp with time zone': 'timestamptz', 'timestamp without time zone': 'timestamp' };

export function sqlToErd(sql) {
  const src = sql.replace(/--[^\n]*/g, '').replace(/\/\*[\s\S]*?\*\//g, '');
  const tables = new Map(), rels = [];
  const head = /create\s+(?:or\s+replace\s+)?(?:temporary\s+|temp\s+)?table\s+(?:if\s+not\s+exists\s+)?([`"\w.[\]]+)\s*\(/gi;
  let h;
  while ((h = head.exec(src))) {
    const b = bodyAt(src, h.index + h[0].length - 1);
    if (!b) break;
    const name = ident(h[1]), cols = [], pks = new Set(), uniq = new Set();
    splitTop(b.body).forEach(part => {
      const p = part.replace(/\s+/g, ' ');
      let m;
      if ((m = p.match(/^(?:constraint \S+ )?primary key\s*\(([^)]*)\)/i))) { m[1].split(',').forEach(c => pks.add(lastPart(c))); return; }
      if ((m = p.match(/^(?:constraint \S+ )?unique(?: key| index)?(?: \S+)?\s*\(([^)]*)\)/i))) { const cs = m[1].split(','); if (cs.length === 1) uniq.add(lastPart(cs[0])); return; }
      if ((m = p.match(/^(?:constraint \S+ )?foreign key\s*\(([^)]*)\)\s*references\s+([`"\w.[\]]+)\s*\(([^)]*)\)/i))) {
        rels.push({ from: name, fc: lastPart(m[1].split(',')[0]), to: ident(m[2]), tc: lastPart(m[3].split(',')[0]) }); return;
      }
      if (/^(?:constraint|key|index|check|exclude|fulltext|spatial)\b/i.test(p)) return;
      if ((m = p.match(/^([`"[]?[\w$]+[`"\]]?)\s+(.+)$/))) {
        const col = unq(m[1]), rest = m[2];
        let type = (rest.match(/^((?:character varying|double precision|timestamp with(?:out)? time zone)|[\w]+)(\s*\([^)]*\))?/i) || ['', ''])[1].toLowerCase();
        type = (TYPE_BACK[type] || type).replace(/\s+/g, '_');
        if (/primary key/i.test(rest)) pks.add(col);
        if (/\bunique\b/i.test(rest)) uniq.add(col);
        const ref = rest.match(/references\s+([`"\w.[\]]+)\s*(?:\(([^)]*)\))?/i);
        if (ref) rels.push({ from: name, fc: col, to: ident(ref[1]), tc: ref[2] ? lastPart(ref[2]) : 'id' });
        cols.push({ col, type });
      }
    });
    tables.set(name, cols.map(c => ({ ...c, key: pks.has(c.col) ? 'pk' : uniq.has(c.col) ? 'unique' : '' })));
    head.lastIndex = b.end;
  }
  const alter = /alter\s+table\s+(?:only\s+)?([`"\w.[\]]+)\s+add\s+(?:constraint\s+\S+\s+)?foreign\s+key\s*\(([^)]*)\)\s*references\s+([`"\w.[\]]+)\s*\(([^)]*)\)/gi;
  let a;
  while ((a = alter.exec(src))) rels.push({ from: ident(a[1]), fc: lastPart(a[2].split(',')[0]), to: ident(a[3]), tc: lastPart(a[4].split(',')[0]) });

  if (!tables.size) return null;
  const fkCols = new Set(rels.map(r => r.from + '.' + r.fc));
  const lines = [];
  tables.forEach((cols, t) => {
    lines.push(`${t} {`);
    cols.forEach(c => {
      const key = c.key === 'pk' && fkCols.has(t + '.' + c.col) ? 'pk,fk' : c.key || (fkCols.has(t + '.' + c.col) ? 'fk' : '');
      lines.push(`  ${c.col.replace(/[^\w-]/g, '_')}${c.type ? ' ' + c.type : ''}${key ? ' ' + key : ''}`);
    });
    lines.push('}');
  });
  // The same key is often declared twice (inline and in an ALTER TABLE).
  const relLines = [...new Set(rels.map(r => `${r.from}.${r.fc.replace(/[^\w-]/g, '_')} > ${r.to}.${r.tc.replace(/[^\w-]/g, '_')}`))];
  if (relLines.length) lines.push('', ...relLines);
  return lines.join('\n') + '\n';
}
