// Builds src/lib/icondata.js from the lucide and simple-icons packages.
// Run with: npm run icons
import { writeFileSync } from 'node:fs';
import { icons as lucide } from 'lucide';
import * as simple from 'simple-icons';

const kebab = s => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/([A-Za-z])([0-9])/g, '$1-$2').toLowerCase();
const attr = v => String(v).replace(/&/g, '&amp;').replace(/"/g, '&quot;');
const node = ([tag, attrs]) => `<${tag} ${Object.entries(attrs).map(([k, v]) => `${k}="${attr(v)}"`).join(' ')}/>`;

// General: Lucide outline icons, 24x24. Aliases that draw the same thing are folded into one entry
// and kept as search words.
const byBody = new Map();
Object.keys(lucide).sort().forEach(k => {
  const body = lucide[k].map(node).join('');
  const name = kebab(k);
  if (byBody.has(body)) byBody.get(body).push(name);
  else byBody.set(body, [name]);
});
const general = [...byBody].map(([body, names]) => {
  names.sort((a, b) => a.length - b.length || a.localeCompare(b));
  return names.length > 1 ? [names[0], body, names.slice(1).join(' ')] : [names[0], body];
}).sort((a, b) => a[0].localeCompare(b[0]));

// Brand logos from Simple Icons (CC0). Trademarks still belong to their owners.
const si = new Map(Object.values(simple).filter(x => x && x.slug).map(x => [x.slug, x]));
const pick = slugs => slugs.split(/\s+/).filter(Boolean).filter(s => si.has(s)).map(s => {
  const x = si.get(s);
  return [s, x.title, x.hex, x.path];
});

const TECH = `
react vuedotjs angular svelte nextdotjs nuxt remix astro solid preact jquery htmx alpinedotjs qwik
typescript javascript python go rust openjdk kotlin swift cplusplus c dotnet php ruby elixir erlang haskell scala clojure lua perl r julia zig dart
rubyonrails django flask fastapi spring springboot laravel symfony nodedotjs deno bun express nestjs fastify koa hono phoenixframework
graphql apollographql trpc hasura
postgresql mysql mariadb sqlite mongodb redis elasticsearch apachecassandra neo4j cockroachlabs clickhouse snowflake supabase firebase prisma sequelize drizzle couchbase scylladb influxdb timescale duckdb dragonfly valkey
docker kubernetes helm terraform ansible pulumi vagrant packer chef puppet
jenkins githubactions gitlab github git bitbucket circleci travisci argo buildkite drone teamcity
nginx apache apachetomcat traefikproxy caddy kong envoyproxy istio linkerd cilium consul vault nomad hashicorp
apachekafka rabbitmq apachespark apacheairflow apachehadoop apachehive apacheflink apachepulsar apachecouchdb apachesolr
grafana prometheus datadog newrelic sentry splunk elastic kibana logstash opentelemetry jaeger dynatrace pagerduty opsgenie
linux ubuntu debian redhat centos alpinelinux fedora archlinux apple android ios macos
stripe paypal auth0 okta keycloak clerk letsencrypt openssl bitwarden snyk dependabot trivy
anthropic huggingface tensorflow pytorch keras scikitlearn numpy pandas jupyter mlflow ollama langchain
discord jira confluence notion figma trello asana linear
intellijidea vim neovim postman swagger openapiinitiative json yaml markdown html5 sass tailwindcss bootstrap mui
webpack vite esbuild babel eslint prettier jest vitest cypress selenium storybook
npm yarn pnpm pypi gradle
minio ceph etcd containerd podman rancher
wireguard openvpn tailscale zapier airtable shopify wordpress strapi contentful sanity gatsby hugo jekyll
redux mobx socketdotio webrtc
databricks airbyte metabase looker apachesuperset googleanalytics mixpanel posthog hotjar
gitea xcode androidstudio flutter reactquery electron tauri ionic capacitor expo
unity unrealengine godotengine blender threedotjs d3 chartdotjs plotly mapbox leaflet openstreetmap googlemaps
youtube spotify x facebook instagram whatsapp telegram gmail googledrive googledocs googlesheets dropbox box zoom googlemeet
`;
const CLOUD = `
googlecloud googlecloudcomposer googlecloudspanner googlecloudstorage googlebigquery googlebigtable googledataflow googledataproc
googlepubsub googlecontaineroptimizedos firebase googlecolab
cloudflare cloudflarepages cloudflareworkers vercel netlify digitalocean akamai vultr hetzner ovh scaleway upcloud exoscale
render flydotio railway alibabacloud yandexcloud openstack apachecloudstack cloudfoundry backblaze wasabi ionos
`;

const tech = pick(TECH), cloud = pick(CLOUD);
const out = `// Generated by scripts/build-icons.mjs. Do not edit by hand.
// General icons: Lucide (ISC license, https://lucide.dev). Logos: Simple Icons (CC0, https://simpleicons.org).
// [name, svg body, search words?] on a 24x24 stroke grid
export const GENERAL = ${JSON.stringify(general)};
// [slug, title, brand hex, path] on a 24x24 fill grid
export const TECH = ${JSON.stringify(tech)};
export const CLOUD = ${JSON.stringify(cloud)};
`;
writeFileSync(new URL('../src/lib/icondata.js', import.meta.url), out);
console.log(`general ${general.length}, tech ${tech.length}, cloud ${cloud.length}, total ${general.length + tech.length + cloud.length}, ${(out.length / 1024).toFixed(0)} KB`);
