/* The Workflows guide's words for each node: what it does, a small example, and what it gives the next
   node. The fields themselves (labels, hints, choices) and where to get each credential are read from
   NODES and CRED_TYPES in flows.js, so the guide always matches the editor.
   what: a sentence or two. ex: an example of using it. out: the items it passes on.
   fields (optional): a note for a field, by its key, where its label isn't enough. */

const APP_OUT = 'One item per input item: the app’s answer (an id, a link, a status). The item’s old fields are replaced, so read them from an earlier node with {{ $node["Name"].json.x }}.';
const LIST_OUT = 'For “list” operations, one item per record the app returns; otherwise the app’s answer for each item.';
const EMAIL = {
  what: 'Sends one email for each item that reaches it.',
  ex: 'To: {{ $json.email }} · Subject: Your order {{ $json.id }} has shipped · Text: Hi {{ $json.name }}, it’s on its way.',
  out: APP_OUT,
  fields: { from: 'Leave blank to use the sender saved in the credential.', html: 'If filled in, it’s sent instead of the plain text.' },
};
const HOOK = (app, where) => ({
  what: `Starts the workflow when ${app} sends an event to this node’s URL. Copy the URL from the node’s settings into ${app}. With a signing secret filled in, requests that aren’t signed with it are refused (401).`,
  ex: where,
  fields: { events: 'Comma-separated. A family name matches all of it: “issues” matches issues.opened and issues.closed. Blank lets every event through.', secret: 'The secret (or signing key) you set or were shown in the app. Recommended, so nobody else can start your workflow.' },
});

export const NODE_GUIDE = {
  /* ---- triggers ---- */
  'trigger.manual': { what: 'Starts the workflow when you press Run workflow (or Run from here). Use it while building, or for workflows you only run yourself.', ex: 'Run by hand → HTTP request → Slack: post today’s numbers whenever you click Run.', out: 'One empty item, so the next node runs once.' },
  'trigger.webhook': { what: 'Gives the workflow a secret URL. Any app or script that calls it starts the workflow, with what it sent. Turn the workflow Active and let it save to listen.', ex: 'curl -X POST <the URL> -H "content-type: application/json" -d \'{"order": 42}\' → then {{ $json.body.order }} is 42.', out: 'One item: { method, query, headers, body }. A JSON or form body arrives already read.', fields: { method: 'Calls with another method get a 405. “Any” accepts all.' } },
  'trigger.schedule': { what: 'Starts the workflow every few minutes, hours or days, or once a day at a time (UTC). Only while the workflow is Active and the server is awake.', ex: 'Every day at 03:30 UTC (09:00 in India) → Hacker News → Email: a morning digest.', out: 'One item: { firedAt } (the time it fired, ISO).', fields: { at: 'In UTC. India is UTC+5:30, so 09:00 IST is 03:30.' } },
  'trigger.form': { what: 'Makes a web form with its own link. Each time someone sends it, the workflow starts with their answers. Share the link (Open shows it); turn the workflow Active first.', ex: 'Fields “Name*”, “Email* (email)”, “Message (long)” → Workline Sheet (add rows): a contact form that fills a sheet.', out: 'One item per answer: each field by a short name (Name → name, Phone number → phoneNumber), plus submittedAt.', fields: { fields: 'One field a line. End the name with * to make it required. Add (long) for a big box, or (email), (number), (date), (tel), (url) for that kind of input.' } },
  'trigger.github': { ...HOOK('GitHub', 'Repository → Settings → Webhooks → Add webhook: Payload URL = this node’s URL, Content type = application/json, Secret = the same secret. Events “issues.opened” → Slack.'), out: 'One item: { event, action, repository, sender, payload } where payload is GitHub’s whole event (e.g. payload.issue.title).' },
  'trigger.stripe': { ...HOOK('Stripe', 'Developers → Webhooks → Add endpoint with this URL; copy the signing secret (whsec_…). Events “checkout.session.completed” → Email the customer.'), out: 'One item: { type, id, object, livemode, created }. object is the thing the event is about (the payment, the invoice…).' },
  'trigger.shopify': { ...HOOK('Shopify', 'Settings → Notifications → Webhooks → Create webhook (JSON) with this URL. Events “orders/create” → Google Sheets: log each order.'), out: 'One item: { topic, shop, data } where data is the order, customer or product.' },
  'trigger.slack': { ...HOOK('Slack', 'api.slack.com/apps → your app → Event Subscriptions: Request URL = this node’s URL (it answers Slack’s check by itself). Subscribe to app_mention → Claude → Slack reply.'), out: 'One item: { type, user, channel, text, ts, team, event }. Messages from bots are skipped, so a reply doesn’t start it again.' },
  'trigger.typeform': { ...HOOK('Typeform', 'Your form → Connect → Webhooks → Add a webhook with this URL (and a secret).'), fields: { secret: HOOK('Typeform').fields.secret }, out: 'One item: { formId, submittedAt, answers, hidden, response }. answers holds each answer by its question’s title.' },
  'trigger.calendly': { ...HOOK('Calendly', 'Create a webhook subscription to this URL with the Calendly API (needs a paid plan); copy its signing key. Events “invitee.created” → Slack: “New booking with {{ $json.name }}”.'), out: 'One item: { event, name, email, eventUri, cancelUrl, rescheduleUrl, answers, payload }.' },
  'trigger.rss': { what: 'Looks at an RSS or Atom feed every few minutes and starts the workflow once for each new post. The first look only notes what’s there.', ex: 'A blog’s feed every 30 min → Telegram: “{{ $json.title }} {{ $json.link }}”.', out: 'One item per new post: { title, link, date, summary }, oldest first.' },
  'trigger.telegram': { what: 'Fetches messages sent to your Telegram bot every few minutes and starts the workflow for each one. The bot must not have a webhook set elsewhere.', ex: 'Telegram message → Claude (prompt: {{ $json.text }}) → Telegram (chat id: {{ $node["Telegram message"].json.chatId }}): a chat bot.', out: 'One item per message: { updateId, chatId, from, text, date, message }.' },
  'trigger.urlchange': { what: 'Fetches a page or API every few minutes and starts the workflow when what comes back is different from last time.', ex: 'A product page every 60 min, text only → Pushover: “The page changed”.', out: 'One item: { url, status, changedAt, hash, previousHash, text } (text: the first 5,000 characters).', fields: { text: 'On: compares the words only, so changing ads or scripts don’t count. Off: any change in the page counts.' } },
  'trigger.sheetrow': { what: 'Checks a Workline sheet every few minutes and starts the workflow for each row added at the bottom since last time. The first row is the header.', ex: 'A sheet with Name, Email → Email: send a welcome to each new person.', out: 'One item per new row: its cells by header name, plus rowNumber.' },

  /* ---- Workline ---- */
  'workline.sheet': { what: 'Reads rows from a sheet in one of your Workline files, or adds each item as a new row at the bottom. The first row is the header: it names the fields.', ex: 'Form → Workline Sheet, Add rows: each answer lands as a row; new fields get a new column.', out: 'Read: one item per row, by header. Add: one item per row added, with its row number.', fields: { values: 'What to write. Blank: the item’s own fields. Or an object: {{ { "Name": $json.name, "Total": $json.total } }}.', sheet: 'Its tab name. Blank: the first sheet.' } },
  'workline.doc': { what: 'Reads a file’s doc, adds text to its end, replaces it, or creates a new file with a doc.', ex: 'Schedule (daily) → Hacker News → Workline Doc, Add to the end: “- {{ $json.title }} {{ $json.url }}”.', out: 'Read: { fileId, title, doc }. Others: { fileId, title } (and the new length).' },
  'workline.diagram': { what: 'Draws a diagram from diagram code into a file (replacing a tab with the same name, else adding one), or reads a file’s diagrams.', ex: 'Claude (“write ERD code for…”) → Workline Diagram, type erd, code: {{ $json.text }}.', out: 'Write: { fileId, name, type }. Read: one item per diagram: { name, type, code }.' },
  'workline.database': { what: 'Runs SQL (or a MongoDB command) on a connection you saved in the Database view. Its password must be remembered there.', ex: 'Schedule → Workline Database: SELECT count(*) AS n FROM orders WHERE created_at > now() - interval \'1 day\' → Slack.', out: 'One item per row returned; for statements without rows, { command, count }.' },

  /* ---- flow ---- */
  'core.if': { what: 'Checks a condition for each item and sends it out of the true or the false output. Connect what should happen to each side.', ex: 'Value {{ $json.total }} · is greater than · 1000 → true: Slack “Big order!” · false: nothing.', out: 'The same items, split between true and false.' },
  'core.switch': { what: 'Compares one value with up to four rules and sends each item out of the first output whose rule matches, or out of “other”.', ex: 'Value {{ $json.country }}; rules IN, US, GB → three different emails, and “other” for the rest.', out: 'The same items, sorted between outputs 1–4 and other.' },
  'core.filter': { what: 'Keeps only the items that meet a condition and drops the rest.', ex: 'Keep items where {{ $json.status }} is equal to paid.', out: 'The items that passed.' },
  'core.merge': { what: 'Waits for two branches and joins their items into one list (input A first, then B).', ex: 'Two HTTP requests (two APIs) → Merge → one Slack message with both.', out: 'All items from A, then all from B.' },
  'core.split': { what: 'Turns a list inside an item into one item per entry.', ex: 'An API returns { orders: [...] } → Split out, field orders → one item per order.', out: 'One item per entry of the list (entries that aren’t objects become { value }).', fields: { field: 'The path to the list, e.g. orders or data.results.' } },
  'core.chunk': { what: 'Groups items into batches of a size.', ex: '250 contacts → Batch of 100 → 3 items → an app that takes 100 at a time.', out: 'One item per batch: { items: [...] }.' },
  'core.limit': { what: 'Keeps only the first (or last) few items.', ex: 'RSS feed → Limit 5 → only the 5 newest posts go on.', out: 'At most that many items.' },
  'core.sort': { what: 'Sorts the items by a field, numbers as numbers and text alphabetically.', ex: 'Sort by score, descending → Limit 3: the top three.', out: 'The same items in order.' },
  'core.dedupe': { what: 'Drops items that repeat, comparing one field or the whole item.', ex: 'Remove duplicates by email before sending a newsletter.', out: 'The first of each kind.' },
  'core.delay': { what: 'Waits a few seconds (up to 60) before passing the items on.', ex: 'Between two API calls that limit how fast you may call them.', out: 'The same items, later.' },
  'core.subflow': { what: 'Hands the items to another workflow file, runs it from its trigger, and brings back what its last steps produced. Workflows can call each other up to 3 deep.', ex: 'A shared “Notify the team” workflow, called from several others.', out: 'The items the other workflow’s last nodes gave.' },
  'core.stop': { what: 'Ends the run with an error and your message. Put it after an IF to stop on bad data.', ex: 'IF {{ $json.amount }} is less than 0 → true: Stop “Negative amount”.', out: 'Nothing: the run stops as failed.' },
  'core.noop': { what: 'Does nothing and passes the items on. Useful as a placeholder or a meeting point; nodes imported from n8n that Workline doesn’t have become this.', ex: 'A placeholder where a step will go later.', out: 'The same items.' },
  'core.code': { what: 'Runs your JavaScript over all the items at once. items is a list of the items’ JSON; return a list (or one object) to pass on. await and fetch work; console.log shows in the output (_logs). It stops after 10 seconds.', ex: 'return items.map(i => ({ ...i, total: i.price * i.qty }));', out: 'Whatever you return, one item per entry. If you return nothing, the items go on unchanged.' },

  /* ---- data ---- */
  'core.set': { what: 'Adds or changes fields on each item. Names may be paths (customer.name).', ex: 'fullName = {{ $json.first }} {{ $json.last }} · paid = true', out: 'The items with those fields set.', fields: { keep: 'Off: each item has only the fields you set here.' } },
  'core.rename': { what: 'Renames fields (or moves them, with paths).', ex: 'name → person.first', out: 'The items with the fields renamed.' },
  'core.aggregate': { what: 'Collects one field from every item into a single list on one item.', ex: 'Field email into emails → one item { emails: [...] } for one email to everybody.', out: 'One item: { <into>: [...] }.' },
  'core.summarize': { what: 'Counts, sums, averages or finds the min/max of a field, overall or per group.', ex: 'Sum of total, grouped by country.', out: 'One item per group: { <group field>, <op> }.' },
  'core.datetime': { what: 'Formats a date, adds or subtracts time, finds the difference between two dates, or turns a date into a Unix timestamp.', ex: 'Add 7 days to {{ $now }} → a due date.', out: 'The items with the result in the field you name (date if blank).', fields: { value: 'A date in almost any form, or a Unix timestamp. Blank: now.' } },
  'core.text': { what: 'Changes text: trim, upper or lower case, replace, split into a list, make a URL slug, cut short, count characters or words.', ex: 'Slug of {{ $json.title }} → my-first-post.', out: 'The items with the result in the field you name (text if blank).' },
  'core.json': { what: 'Turns JSON text into an object (parse), or an object into JSON text (stringify).', ex: 'An API sends a field as text: parse it to read inside it.', out: 'The items with the field converted.' },
  'core.regex': { what: 'Finds text with a regular expression. With a group in brackets it gives the group; with the g flag, every match.', ex: 'Pattern #(\\d+) on “Fixes #42” → 42.', out: 'The items with matches (or null) in the field you name.' },
  'core.csv': { what: 'Reads CSV text into one item per row (the first line is the header), or builds CSV text from the items.', ex: 'HTTP request (a .csv file) → CSV, read → Workline Sheet, add rows.', out: 'Read: one item per row. Build: one item { csv }.' },
  'core.crypto': { what: 'Hashes (SHA-256, MD5…), signs with HMAC, encodes or decodes base64, or makes a UUID or random string.', ex: 'HMAC SHA-256 of the body with your secret, to sign a call to an API.', out: 'The items with the result in the field you name (hash if blank).' },
  bitly: { what: 'Shortens a link with your Bitly account.', ex: 'Link {{ $json.url }} → share {{ $json.shortUrl }} in an SMS.', out: 'The items with the short link added (shortUrl).' },
  'util.qrcode': { what: 'Makes a link to a QR code image holding any text or link. Nothing is sent anywhere until the image is opened.', ex: 'Text {{ $json.ticketUrl }} → put {{ $json.qrCode }} in an email as <img src="…">.', out: 'The items with the image link added (qrCode).' },

  /* ---- AI ---- */
  'ai.claude': { what: 'Asks Claude, using the Workline server’s own key (no credential needed). Counts towards the account’s daily AI allowance.', ex: 'Prompt: Summarise this support email in one line and say if it’s urgent: {{ $json.body }}', out: 'One item per input item: { text } — Claude’s answer.', fields: { system: 'Instructions for how to answer, e.g. “Reply in JSON only.”' } },
  openai: { what: 'Asks an OpenAI model, or any OpenAI-style API (set its base URL in the credential).', ex: 'Model gpt-4o-mini · Prompt: Write a friendly reply to: {{ $json.text }}', out: 'One item per input item: { text, model, usage }.' },
  gemini: { what: 'Asks a Google Gemini model.', ex: 'Prompt: Translate to Hindi: {{ $json.text }}', out: 'One item per input item: { text }.' },
  deepl: { what: 'Translates text with DeepL.', ex: 'Text {{ $json.message }} · Into Hindi.', out: 'The items with translation and detectedLanguage added.' },

  /* ---- communication ---- */
  'app.slack': { what: 'Posts a message to Slack: with an incoming webhook URL (simplest: it posts to the webhook’s channel), or with a bot token to any channel.', ex: 'Text: New order {{ $json.id }} for ₹{{ $json.total }}', out: APP_OUT, fields: { channel: 'Only with a bot token: #general or a channel id.' } },
  'app.discord': { what: 'Posts a message in a Discord channel through its webhook.', ex: 'Content: 🚀 Deployed {{ $json.version }}', out: APP_OUT },
  'app.telegram': { what: 'Sends a message from your Telegram bot to a chat.', ex: 'Chat id {{ $json.chatId }} · Text: Got it, thanks!', out: APP_OUT, fields: { chatId: 'Message your bot once, then open api.telegram.org/bot<token>/getUpdates to see your chat id, or use the Telegram message trigger.' } },
  whatsapp: { what: 'Sends a WhatsApp text through the WhatsApp Cloud API (Meta). Outside a 24-hour reply window, WhatsApp only allows approved templates.', ex: 'To 919876543210 · Text: Your table is ready.', out: APP_OUT },
  'app.teams': { what: 'Posts a message to a Microsoft Teams channel through its incoming webhook.', ex: 'Text: Build {{ $json.id }} failed', out: APP_OUT },
  'app.googlechat': { what: 'Posts a message to a Google Chat space through its webhook.', ex: 'Text: New lead: {{ $json.name }}', out: APP_OUT },
  'app.mattermost': { what: 'Posts a message to a Mattermost channel through its incoming webhook.', ex: 'Text: Backup finished', out: APP_OUT },
  'app.email': { ...EMAIL, fields: { html: EMAIL.fields.html }, what: 'Sends an email through your own SMTP server (Gmail with an app password works).' },
  sendgrid: { ...EMAIL, fields: { html: EMAIL.fields.html }, what: 'Sends an email through SendGrid.' },
  resend: { ...EMAIL, fields: { html: EMAIL.fields.html }, what: 'Sends an email through Resend.' },
  mailgun: { ...EMAIL, what: 'Sends an email through Mailgun.' },
  postmark: { ...EMAIL, what: 'Sends an email through Postmark.' },
  brevo: { ...EMAIL, what: 'Sends an email through Brevo (formerly Sendinblue). To may hold several addresses, separated by commas.' },
  twilio: { what: 'Sends a text message (SMS) with Twilio.', ex: 'To {{ $json.phone }} · Message: Your code is {{ $json.code }}', out: APP_OUT, fields: { to: 'With the country code: +91…' } },
  mailchimp: { what: 'Adds someone to a Mailchimp audience (list).', ex: 'Form → Mailchimp: email {{ $json.email }}, first name {{ $json.name }}.', out: APP_OUT },
  ntfy: { what: 'Sends a push notification to your phone with ntfy (free; install the ntfy app and subscribe to your topic). The credential is only for your own server or a protected topic.', ex: 'Topic my-alerts-8xk2 · Message: The site is down', out: APP_OUT, fields: { topic: 'Anyone who knows a topic on ntfy.sh can read it: pick something hard to guess.' } },
  pushover: { what: 'Sends a push notification to your phone with Pushover.', ex: 'Title: Payment · Message: ₹{{ $json.amount }} from {{ $json.email }}', out: APP_OUT },

  /* ---- productivity ---- */
  'app.notion': { what: 'Adds a page to a Notion database, or lists its pages. Share the database with your integration first.', ex: 'Form → Notion, create page: title {{ $json.name }}, content {{ $json.message }}.', out: LIST_OUT, fields: { titleProperty: 'The name of the database’s title column (usually Name).' } },
  'google.sheets': { what: 'Reads rows from a Google Sheet, or adds a row. Uses a service account: share the sheet with its email.', ex: 'Append values {{ [$json.name, $json.email, $now] }} to Sheet1.', out: 'Read: one item per row (the first row names the fields). Append: what was updated.', fields: { spreadsheetId: 'The long id in the sheet’s address, between /d/ and /edit.', values: 'A list, or values separated by commas.' } },
  'google.calendar': { what: 'Lists upcoming events, or creates one. Share the calendar with the service account’s email.', ex: 'Calendly → Google Calendar, create: summary {{ $json.name }}, start/end from the booking.', out: LIST_OUT },
  airtable: { what: 'Lists, creates or updates records in an Airtable table.', ex: 'Create in table Leads: fields {"Name": "{{ $json.name }}"}', out: LIST_OUT, fields: { formula: 'An Airtable formula to filter, e.g. {Status} = "Open".' } },
  trello: { what: 'Creates a card in a Trello list, or lists its cards.', ex: 'GitHub issue → Trello card: name {{ $json.payload.issue.title }}.', out: LIST_OUT },
  asana: { what: 'Creates a task in an Asana project, or lists its tasks.', ex: 'Name: Call {{ $json.name }} · Due on {{ $json.date }}', out: LIST_OUT },
  clickup: { what: 'Creates a task in a ClickUp list, or lists its tasks.', ex: 'Name: Review {{ $json.title }}', out: LIST_OUT },
  todoist: { what: 'Adds a task to Todoist, or lists tasks (with a filter such as today).', ex: 'Content: Pay {{ $json.vendor }} · Due: tomorrow', out: LIST_OUT },
  wordpress: { what: 'Creates a post on a WordPress site, or lists posts. Uses an application password.', ex: 'Claude (writes a post) → WordPress, draft: title {{ $json.title }}, content {{ $json.text }}.', out: LIST_OUT },

  /* ---- developer ---- */
  'core.http': { what: 'Calls any web address or API. The most flexible node: if an app has no node of its own, use this with its API.', ex: 'GET https://api.github.com/repos/{{ $json.repo }} · or POST JSON {{ { "name": $json.name } }} to your own API.', out: 'The JSON answer (a list becomes one item per entry); other answers as { status, body }.', fields: { failOnError: 'Off: an error answer (404, 500…) goes on as an item instead of stopping the run.', body: 'JSON text, or an expression giving an object.' } },
  'app.github': { what: 'Creates an issue, lists issues, or reads a repository on GitHub.', ex: 'Form (bug report) → GitHub, create issue: title {{ $json.summary }}.', out: LIST_OUT },
  gitlab: { what: 'Creates or lists issues in a GitLab project (gitlab.com or your own server).', ex: 'Project id 12345 · Title {{ $json.title }}', out: LIST_OUT },
  jira: { what: 'Creates a Jira issue, reads one, or searches with JQL.', ex: 'JQL: project = APP AND status = "To Do" → Slack summary.', out: LIST_OUT },
  linear: { what: 'Creates or lists issues in a Linear team.', ex: 'Title {{ $json.title }} · Team id from Linear’s settings.', out: LIST_OUT },
  zendesk: { what: 'Creates a Zendesk ticket, or lists tickets.', ex: 'Form → Zendesk: subject {{ $json.subject }}, requester {{ $json.email }}.', out: LIST_OUT },
  pagerduty: { what: 'Raises, acknowledges or resolves a PagerDuty alert (Events API v2).', ex: 'Page changed (status page) → PagerDuty: raise “Site is down”, dedup key site-down.', out: APP_OUT, fields: { dedupKey: 'Use the same key to acknowledge or resolve the alert later.' } },

  /* ---- sales & payments ---- */
  hubspot: { what: 'Creates a contact in HubSpot, or lists contacts.', ex: 'Form → HubSpot: email {{ $json.email }}, first name {{ $json.name }}.', out: LIST_OUT },
  pipedrive: { what: 'Creates a person or a deal in Pipedrive, or lists deals.', ex: 'Create deal: title {{ $json.company }}, value {{ $json.budget }}.', out: LIST_OUT },
  stripe: { what: 'Lists or creates customers, lists payments, or reads your balance in Stripe.', ex: 'Schedule (daily) → Stripe, list payments → Summarize sum of amount → Slack.', out: LIST_OUT },
  shopify: { what: 'Lists orders or products in your Shopify shop.', ex: 'Schedule → Shopify, open orders → Limit 10 → Email.', out: LIST_OUT },

  /* ---- storage & feeds ---- */
  'app.database': { what: 'Runs a query on a PostgreSQL, MySQL, SQL Server or MongoDB database from a connection string in the credential.', ex: 'INSERT INTO leads (email) VALUES (\'{{ $json.email }}\')', out: 'One item per row returned; otherwise { command, count }.', fields: { sql: 'Expressions are pasted in as text: only use values you trust, or check them first with IF.' } },
  supabase: { what: 'Gets, inserts, updates or deletes rows in a Supabase table.', ex: 'Insert into signups: row {"email": "{{ $json.email }}"}', out: LIST_OUT, fields: { filter: 'Supabase (PostgREST) filters: id=eq.1&status=eq.open' } },
  dropbox: { what: 'Lists a Dropbox folder, or saves text as a file.', ex: 'Path /reports/{{ $now.slice(0, 10) }}.csv · Content {{ $json.csv }}', out: LIST_OUT },
  'data.rss': { what: 'Reads the latest posts of an RSS or Atom feed (every time it runs; use the “New in a feed” trigger to get only new ones).', ex: 'Schedule (daily) → RSS feed → Limit 5 → Email digest.', out: 'One item per post: { title, link, date, summary }.' },
  'data.hackernews': { what: 'Gets top, new, best, Ask HN or Show HN stories from Hacker News.', ex: 'Top 10 → Filter score ≥ 300 → Telegram.', out: 'One item per story: { id, title, url, score, by, comments, time }.' },
  'data.weather': { what: 'Gets the current weather anywhere from Open-Meteo (free, no key).', ex: 'Latitude 28.61, longitude 77.21 (Delhi) → IF precipitation > 0 → “Take an umbrella”.', out: 'One item: temperature_2m, relative_humidity_2m, wind_speed_10m, precipitation, weather_code, units, timezone.' },
  'web.page': { what: 'Opens a web page and pulls out what you need: its text, every link, its tables, or exactly the parts a CSS selector points to. No browser runs, so it’s fast and free, but pages that build themselves with JavaScript look empty: use the Browser node for those.', ex: 'Schedule (daily) → Web page (a shop’s product list; Named fields, Repeat for each .product: name → h2, price → .price, link → a @href) → Filter price < 2000 → Telegram.', out: 'Text: one item { url, title, description, text }. Links, tables, selector: one item per result. Named fields: one item (or one per block).', fields: { extract: 'Text: the page’s title, description and words. Links: one item per link. Tables: one item per row, named by the header. CSS selector: one item per element found. Named fields: pull several things at once.', selector: 'Which part of the page. Examples: h1 · .price · #main a · table.results. Add @href (or @src, @content…) to read an attribute instead of the text. For Text, it limits the text to that part.', each: 'For lists (products, posts, jobs): the selector of one block; each block becomes an item, and the fields are read inside it.', fields: 'One row per field: a name, and a CSS selector (with @attribute if needed). E.g. title → h2 · price → .price · link → a @href.' } },
  'web.browser': { what: 'Opens the page in a real Chrome browser (through Browserless, a hosted browser service), so pages built with JavaScript work. It can also do steps first — click, type, press keys, wait — then read the page, or take a screenshot or a PDF.', ex: 'Steps: type #search | iphone 15 · press Enter · wait .s-result-item → Named fields, Repeat for each .s-result-item: title → h2, price → .a-price-whole.', out: 'Read and Steps: like Web page (plus screenshot, if asked). Screenshot or PDF: one item { url, screenshot | pdf, bytes } where the file is a data: link you can put in an email or save.', fields: { ...{ extract: 'Text: the page’s title, description and words. Links: one item per link. Tables: one item per row, named by the header. CSS selector: one item per element found. Named fields: pull several things at once.', selector: 'Which part of the page. Examples: h1 · .price · #main a · table.results. Add @href (or @src, @content…) to read an attribute instead of the text. For Text, it limits the text to that part.', each: 'For lists (products, posts, jobs): the selector of one block; each block becomes an item, and the fields are read inside it.', fields: 'One row per field: a name, and a CSS selector (with @attribute if needed). E.g. title → h2 · price → .price · link → a @href.' }, steps: 'One step a line: click <selector> · type <selector> | <text> · press <key> (Enter, Tab…) · wait <selector> · sleep <milliseconds> · scroll (to the bottom) · goto <address>. Lines starting with # are ignored.', waitFor: 'The page is read once this appears, for content that loads late.' } },
  'data.currency': { what: 'Converts an amount between currencies at today’s rate (European Central Bank rates, via Frankfurter; free).', ex: 'Amount {{ $json.price }} from USD to INR.', out: 'The items with converted, rate, from, to and date added.' },
};

/* Where each kind of credential comes from, step by step (shown under “Set it up”). The fields named
   here are the ones the credential dialog asks for (CRED_TYPES in flows.js). */
export const CRED_SETUP = {
  slack: ['Simplest (one channel): go to api.slack.com/apps → Create New App → From scratch, and pick your workspace.', 'Open Incoming Webhooks → turn it on → Add New Webhook to Workspace → choose the channel → Allow.', 'Copy the webhook URL (https://hooks.slack.com/services/…) into Webhook URL.', 'To post to any channel instead: OAuth & Permissions → add the chat:write scope → Install to Workspace → copy the Bot User OAuth Token (xoxb-…) into Bot token, and invite the bot to each channel (/invite @your-app).'],
  discord: ['In Discord, open the channel’s settings (the gear by its name) → Integrations → Webhooks → New Webhook.', 'Name it, then press Copy Webhook URL.', 'Paste it into Webhook URL.'],
  telegram: ['In Telegram, message @BotFather and send /newbot.', 'Give it a name, and a username ending in “bot”.', 'BotFather replies with a token like 123456:ABC-…: paste it into Bot token.', 'Send your bot a message once, so it may write to you.'],
  whatsapp: ['Go to developers.facebook.com → My Apps → Create App → Business, then add the WhatsApp product.', 'Under WhatsApp → API Setup, copy the access token (temporary; make a permanent one with a system user) into Access token.', 'Copy the Phone number ID shown there into Phone number id.', 'While testing, add the numbers you send to under “To”.'],
  chatWebhook: ['Microsoft Teams: in the channel, ⋯ → Workflows (or Connectors) → “Post to a channel when a webhook request is received” → copy the URL.', 'Google Chat: open the space → Apps & integrations → Webhooks → Add webhook → copy the URL.', 'Mattermost: Integrations → Incoming Webhooks → Add → choose the channel → copy the URL.', 'Paste it into Webhook URL.'],
  smtp: ['Write your mail server as a URL: smtps://USER:PASSWORD@HOST:465 (or smtp://…:587).', 'Gmail: turn on 2-Step Verification, then myaccount.google.com → Security → App passwords → make one, and use smtps://you@gmail.com:THE-APP-PASSWORD@smtp.gmail.com:465.', 'If the user name or password has @ or : in it, write it as %40 or %3A.', 'Fill in From, e.g. Workline <you@gmail.com>.'],
  sendgrid: ['app.sendgrid.com → Settings → Sender Authentication: verify a sender address (or your domain).', 'Settings → API Keys → Create API Key (Restricted, with Mail Send) → copy it into API key.', 'Put the verified address in From.'],
  resend: ['resend.com → Domains → add and verify your domain (or use onboarding@resend.dev to try it).', 'API Keys → Create API Key → copy it into API key.', 'Put an address on that domain in From.'],
  twilio: ['console.twilio.com → the Account Info box on the home page.', 'Copy the Account SID and Auth Token into their fields.', 'Phone Numbers → buy a number (or use your trial number) and put it in From number, with + and the country code.', 'On a trial account, verify the numbers you send to.'],
  mailchimp: ['In Mailchimp, click your profile → Profile → Extras → API keys → Create A Key.', 'Copy the whole key (it ends in -us21 or similar) into API key.', 'For the node: Audience → Settings → Audience name and defaults shows the Audience ID.'],
  ntfy: ['Only needed for your own ntfy server or a protected topic; for public ntfy.sh topics, leave the node without a credential.', 'Server: your ntfy address. Access token: in ntfy’s web app → Account → Access tokens.'],
  notion: ['notion.so/my-integrations → New integration → pick the workspace → Save.', 'Copy the Internal Integration Secret into Integration secret.', 'Open the database in Notion → ⋯ → Connections → add your integration (otherwise Notion says it can’t find it).', 'The database id is the 32 characters in its link, before ?v=.'],
  google: ['console.cloud.google.com → create (or pick) a project.', 'APIs & Services → Library: enable the Google Sheets API and/or the Google Calendar API.', 'IAM & Admin → Service Accounts → Create service account (no roles needed) → open it → Keys → Add key → JSON. A file downloads.', 'Open the file and paste all of it into Key (JSON).', 'Share your sheet or calendar with the service account’s email (…@….iam.gserviceaccount.com) as an editor.'],
  airtable: ['airtable.com/create/tokens → Create new token.', 'Scopes: data.records:read and data.records:write. Access: add your base.', 'Copy the token into Token. The base id (app…) is in the base’s link.'],
  trello: ['trello.com/power-ups/admin → New → make a Power-Up (any name) → API key → Generate a new API key.', 'Copy the API key, then follow the “Token” link next to it → Allow → copy the token.', 'To find a list id: open a card in the list, add .json to its link, and look for idList.'],
  asana: ['app.asana.com/0/my-apps (or your profile picture → My settings → Apps → Developer apps) → Create new token.', 'Copy it into Token. A project id is the number in the project’s link.'],
  clickup: ['In ClickUp: your avatar → Settings → Apps → API Token → Generate.', 'Copy it (pk_…) into API token. A list id is in the list’s link (…/li/12345).'],
  todoist: ['todoist.com → Settings → Integrations → Developer → copy the API token.', 'Paste it into API token.'],
  wordpress: ['In WordPress admin: Users → Profile → Application Passwords → name it “Workline” → Add New.', 'Copy the password it shows (spaces are fine) into Application password.', 'Site: your site’s address. Username: your WordPress user name. The site must use https.'],
  github: ['github.com → Settings → Developer settings → Personal access tokens → Fine-grained tokens → Generate new token.', 'Repository access: the repositories to use. Permissions: Issues (read and write) and Contents (read).', 'Copy the token into Token.'],
  gitlab: ['GitLab → your avatar → Preferences → Access Tokens → Add new token with the api scope.', 'Copy it into Token. For your own GitLab server, put its address in Server.', 'A project id is shown on the project’s home page.'],
  jira: ['id.atlassian.com/manage-profile/security/api-tokens → Create API token → copy it into API token.', 'Site: your-team.atlassian.net. Email: the email you sign in to Atlassian with.'],
  linear: ['Linear → Settings → Security & access (or API) → Personal API keys → New key.', 'Copy it into API key. The team id is under Settings → Teams.'],
  zendesk: ['Zendesk Admin Center → Apps and integrations → APIs → Zendesk API → turn on Token access → Add API token.', 'Copy it into API token. Subdomain: the “your-team” in your-team.zendesk.com. Email: an agent’s email.'],
  hubspot: ['HubSpot → Settings (the gear) → Integrations → Private Apps → Create a private app.', 'Scopes: crm.objects.contacts.read and crm.objects.contacts.write → Create app → copy the access token into Access token.'],
  pipedrive: ['Pipedrive → your avatar → Personal preferences → API → copy your personal API token.', 'Paste it into API token. Company domain is optional (your-company.pipedrive.com).'],
  stripe: ['dashboard.stripe.com → Developers → API keys.', 'Copy the Secret key (sk_test_… while testing, sk_live_… for real), or create a Restricted key with only what you need.', 'Paste it into Secret key.'],
  shopify: ['Shopify admin → Settings → Apps and sales channels → Develop apps → Create an app.', 'Configuration → Admin API scopes: read_orders and read_products (and any others you need) → Save → Install app.', 'API credentials → reveal the Admin API access token (shown only once) → copy it into Admin API token.', 'Shop: your-shop.myshopify.com.'],
  openai: ['platform.openai.com → API keys → Create new secret key → copy it into API key (and add credit under Billing).', 'For another OpenAI-style service (Groq, OpenRouter, a local server), put its base URL, e.g. https://api.groq.com/openai/v1, in Base URL.'],
  gemini: ['aistudio.google.com → Get API key → Create API key.', 'Copy it into API key.'],
  database: ['Pick the Kind, and write a connection string: postgres://USER:PASSWORD@HOST:5432/DB, mysql://…:3306/DB, mssql://…:1433/DB or mongodb+srv://USER:PASSWORD@CLUSTER/DB.', 'The database must accept connections from the internet (from the Workline server), as Neon, Supabase or MongoDB Atlas do. A database on your own computer can’t be reached.'],
  supabase: ['supabase.com → your project → Project Settings → API (Data API).', 'Copy the Project URL into Project URL, and the service_role key into Service role key.', 'The service role key skips row-level security: keep it secret.'],
  dropbox: ['dropbox.com/developers/apps → Create app → Scoped access → App folder (or Full Dropbox).', 'Permissions: files.content.write and files.content.read → Submit.', 'Settings → Generated access token → Generate → copy it into Access token. These tokens expire after a few hours.'],
  bearer: ['For an API that wants “Authorization: Bearer <token>”: paste the token into Token.'],
  header: ['For an API that wants its key in a header: Header name, e.g. X-API-Key; Value, the key.'],
  mailgun: ['app.mailgun.com → Sending → Domains → add and verify your domain (or use the sandbox domain to try).', 'API keys (under your account or the domain) → create a key → copy it into API key.', 'Domain: e.g. mg.example.com. Region: EU if your account is on Mailgun’s EU servers. From: an address on that domain.'],
  postmark: ['account.postmarkapp.com → Servers → your server → API Tokens → copy the Server API token into Server token.', 'Sender Signatures: confirm the address (or domain) you send from, and put it in From.'],
  brevo: ['app.brevo.com → your name (top right) → SMTP & API → API Keys → Generate a new API key → copy it into API key.', 'Senders, domains & dedicated IPs → Senders: add and verify your sender, and put it in From.'],
  pushover: ['pushover.net → sign in: your User Key is on the front page → copy it into User key.', 'Create an Application/API Token (at the bottom of that page) → copy it into Application token.', 'Install the Pushover app on your phone and sign in.'],
  pagerduty: ['PagerDuty → Services → your service → Integrations → Add an integration → Events API V2.', 'Copy the Integration Key into Routing key.'],
  deepl: ['Sign up for DeepL API Free or Pro, then go to deepl.com/your-account/keys.', 'Copy the authentication key (free keys end in :fx) into API key.'],
  browserless: ['browserless.io → Sign up (the free plan gives some browser time each month).', 'Your account page shows your API token: copy it into API token.', 'Server: leave blank (their US server), or put another region’s address from your account page, or your own Browserless server.'],
  bitly: ['app.bitly.com → Settings → Developer settings → API → enter your password → Generate token.', 'Copy it into Access token.'],
};

// Extra steps for nodes that need something done in the other app, beyond the credential and the fields.
export const NODE_SETUP = {
  'trigger.webhook': ['Copy the Webhook URL from the node’s settings.', 'Paste it where the other app or script sends its calls (its “webhook”, “callback” or “notification URL”).', 'Pick the method it uses, or leave Any.'],
  'trigger.schedule': ['Choose Every… (minutes, hours or days), or Every day at a time in UTC.'],
  'trigger.form': ['Write a title, and the fields one a line (end a name with * to make it required).', 'Turn the workflow Active, wait for Saved, then press Open to see the form and share its link.'],
  'trigger.github': ['In the repository: Settings → Webhooks → Add webhook.', 'Payload URL: the node’s URL. Content type: application/json. Secret: make one up, and put the same in the node’s Signing secret.', 'Choose the events to send (or “Send me everything” and filter with Only these events) → Add webhook. GitHub sends a ping first, which Workline accepts.'],
  'trigger.stripe': ['dashboard.stripe.com → Developers → Webhooks → Add endpoint.', 'Endpoint URL: the node’s URL. Select the events, e.g. checkout.session.completed → Add endpoint.', 'Reveal the Signing secret (whsec_…) and paste it into the node.'],
  'trigger.shopify': ['Shopify admin → Settings → Notifications → Webhooks → Create webhook.', 'Event: e.g. Order creation. Format: JSON. URL: the node’s URL → Save.', 'Copy the key shown under the list of webhooks (“Your webhooks will be signed with…”) into Signing secret.'],
  'trigger.slack': ['api.slack.com/apps → your app → Event Subscriptions → Enable Events.', 'Request URL: the node’s URL. Turn the workflow Active first; Slack checks the URL and shows Verified.', 'Subscribe to bot events, e.g. app_mention or message.channels → Save Changes → reinstall the app if asked.', 'Basic Information → Signing Secret → copy it into the node.'],
  'trigger.typeform': ['Your form → Connect → Webhooks → Add a webhook → paste the node’s URL.', 'Edit the webhook to set a secret (optional; put the same in the node), and switch it on.'],
  'trigger.calendly': ['Make a personal access token: Calendly → Integrations → API & Webhooks.', 'Create a webhook subscription with Calendly’s API (POST https://api.calendly.com/webhook_subscriptions) with the node’s URL as url, the events (invitee.created, invitee.canceled) and a signing_key.', 'Put the same signing key in the node.'],
  'trigger.rss': ['Paste the feed’s address (often /feed, /rss or /atom.xml on the site).', 'Choose how often to check, in minutes.'],
  'trigger.telegram': ['Make sure the bot has no webhook set elsewhere (if it had one, open api.telegram.org/bot<token>/deleteWebhook once).', 'In groups, the bot only sees messages meant for it, unless you turn its privacy mode off with @BotFather (/setprivacy).'],
  'trigger.urlchange': ['Paste the page or API address, and choose how often to check.', 'Leave “Compare the text only” on for web pages, so changing ads and scripts don’t count.'],
  'trigger.sheetrow': ['Pick the Workline file and, if it has several, the sheet’s name.', 'Its first row must be the header; new rows go below the last one.'],
  'workline.sheet': ['Pick the file (one with a sheet) and the sheet’s name, or leave it blank for the first.', 'Choose Read rows or Add rows.'],
  'workline.diagram': ['Pick the file, name the tab and choose the diagram type. The code uses Workline’s diagram language (see “How to use Workline”).'],
  'workline.database': ['In the Database view, save a connection (not SQLite) with Remember password on.', 'Pick it in the node and write the query.'],
  'core.if': ['Fill in Value (usually an expression like {{ $json.status }}), the check, and Against.', 'Connect the next step to the true dot, the false dot, or both.'],
  'core.switch': ['Fill in Value, and Rule 1–4 with the values to match.', 'Connect each numbered dot (and “other”) to its own next step.'],
  'core.merge': ['Connect one branch to input A and the other to input B.'],
  'core.subflow': ['Save the other workflow first; it needs a trigger (Run by hand is fine).', 'Pick it in the node.'],
  'core.code': ['Write JavaScript that returns the new items, e.g. return items.filter(i => i.total > 0);'],
  'ai.claude': ['Nothing to connect: it uses the Workline server’s Claude key (ANTHROPIC_API_KEY on the server).'],
  'app.notion': ['Share the database with your integration (⋯ → Connections), then paste the database id.'],
  'google.sheets': ['Share the sheet with the service account’s email (from the key file) as an editor.', 'Copy the spreadsheet id from its link, and set the range (e.g. Sheet1 or Sheet1!A:D).'],
  'google.calendar': ['Calendar settings → Share with specific people → add the service account’s email with “Make changes to events”.', 'Calendar id: under Integrate calendar (for your main calendar, it is your email).'],
  'core.http': ['Fill in the method and URL; add query or header rows if the API wants them.', 'If the API needs a key, add a Bearer token or Header credential.'],
  whatsapp: ['The number you send to goes with the country code and no +, e.g. 919876543210.'],
  'web.page': ['Paste the page address (it can hold expressions, e.g. https://example.com/item/{{ $json.id }}).', 'Choose what to take. To find a selector: open the page in Chrome, right-click the thing → Inspect, and look at its tag and class (e.g. span class="price" → .price).', 'Run it and check Output; adjust the selector until it gives what you want.'],
  'web.browser': ['Choose what to do: read the page, do steps then read, a screenshot, or a PDF.', 'For steps, write one a line (see Steps below). Find selectors with right-click → Inspect in Chrome.', 'If the content loads late, fill in Wait for with a selector of something that appears when it’s ready.'],
  'data.weather': ['Find the place’s latitude and longitude (right-click it on Google Maps).'],
};
